on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: worker
          command: publish index.js --name gts --compatibility-date 2023-01-16
          secrets: |
            PROXY_URL_BASE
        env:
          PROXY_URL_BASE: ${{ secrets.PROXY_URL_BASE }}
